name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"       # e.g. v0.1.0

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # needed for trusted publishing (optional)
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.2'  # or latest stable

      - name: Configure Poetry for publishing
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish --no-interaction --skip-existing
